version: "3.8"
services:
  db:
    container_name: pg_container_blitz-quiz-app
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: blitz-quiz-app
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin4_container_blitz-quiz-app
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
