export { UpdateGame } from "./games/mutations/updateGame"
export { CreateGame } from "./games/mutations/createGame"
export { UpdateQuestion } from "./questions/mutations/updateQuestion"
export { CreateQuestion } from "./questions/mutations/createQuestion"
export { default as UpdateAnswer } from "./answers/mutations/updateAnswer"
export { default as CreateAnswer } from "./answers/mutations/createAnswer"
